const H4={'Content-Type':'application/json','X-Genevieve-Stage4':'1'};
const state={dogs:[],park:null,ready:false};
const $=s=>document.querySelector(s);
const text=(s,v)=>{const e=$(s);if(e)e.textContent=v;};
async function api(url,o={}){const r=await fetch(url,{cache:'no-store',credentials:'same-origin',...o});let d={};try{d=await r.json();}catch{}if(!r.ok){const e=new Error(d.error||`request-failed-${r.status}`);e.status=r.status;e.data=d;throw e;}return d;}
function option(value,label){const o=document.createElement('option');o.value=value;o.textContent=label;return o;}
function item(label,value){const li=document.createElement('li');const strong=document.createElement('strong');strong.textContent=`${label}: `;li.append(strong,document.createTextNode(value));return li;}
function renderList(rootSelector,title,values=[]){const root=$(rootSelector);if(!root)return;root.replaceChildren();if(title){const h=document.createElement('h4');h.textContent=title;root.append(h);}const ul=document.createElement('ul');if(!values.length){const li=document.createElement('li');li.textContent='None recorded.';ul.append(li);}else for(const value of values){const li=document.createElement('li');li.textContent=typeof value==='string'?value:(value.meaning||`${value.factor}: ${value.value??'UNKNOWN'}`);ul.append(li);}root.append(ul);}
function renderScale(){const r=$('#stage4-risk-scale');if(!r)return;r.replaceChildren();const bands=[['1–3','Green','Lower risk'],['4–5','Yellow','Caution'],['6–7','Amber','High concern'],['8–10','Red','Highest concern']];for(const [range,name,label] of bands){const d=document.createElement('div');d.className=`risk-band risk-${name.toLowerCase()}`;const s=document.createElement('strong');s.textContent=range;const n=document.createElement('span');n.textContent=name;const l=document.createElement('small');l.textContent=label;d.append(s,n,l);r.append(d);}}
function renderDogOptions(){const select=$('#stage4-suitability-dog');if(select){const current=select.value;select.replaceChildren(option('','Choose a saved mate'));for(const d of state.dogs)select.append(option(d.dog_id,d.name));if([...select.options].some(o=>o.value===current))select.value=current;}
 const root=$('#stage4-compatibility-dogs');if(root){root.replaceChildren();if(!state.dogs.length){const p=document.createElement('p');p.className='microcopy';p.textContent='Save at least two mate profiles before a compatibility review.';root.append(p);}else for(const d of state.dogs){const label=document.createElement('label');label.className='check-chip';const input=document.createElement('input');input.type='checkbox';input.name='stage4DogIds';input.value=d.dog_id;label.append(input,document.createTextNode(d.name));root.append(label);}}
 updateButtons();}
function updateButtons(){const suitability=$('#stage4-suitability-submit'),compat=$('#stage4-compatibility-submit');if(suitability)suitability.disabled=!(state.ready&&state.park&&state.dogs.length);if(compat)compat.disabled=!(state.ready&&state.dogs.length>=2);}
function renderHeat(heat,parkName='Selected park'){const root=$('#stage4-heat-result');if(!root)return;root.replaceChildren();const h=document.createElement('h4');h.textContent='Heat & surface check';const p=document.createElement('p');p.textContent=`${parkName}: live weather and numeric surface-temperature estimation remain gated. Static shade/water facts are shown without assuming current conditions.`;const ul=document.createElement('ul');ul.append(item('Shade recorded',heat?.shadeRecorded??'UNKNOWN'),item('Dog water recorded',heat?.dogWaterRecorded??'UNKNOWN'),item('Tap water recorded',heat?.tapWaterRecorded??'UNKNOWN'),item('Live weather',heat?.liveWeatherEnabled?'ENABLED':'NOT CONNECTED'),item('Surface heat estimate',heat?.surfaceHeatEstimateEnabled?'ENABLED':'DISABLED PENDING VALIDATION'));root.append(h,p,ul);}
function renderSuitability(a){const root=$('#stage4-suitability-result');if(!root)return;root.replaceChildren();const h=document.createElement('h3');h.textContent=`${a.park?.name??'Selected park'} × ${a.dog?.name??'selected mate'}`;const status=document.createElement('p');status.className='stage4-gated';status.textContent='Numerical score: NOT ISSUED — expert policy gate pending';const g=document.createElement('p');g.textContent=a.guidance;root.append(h,status,g);renderList('#stage4-suitability-reasons','What was checked',(a.reasons||[]).map(x=>`${x.factor}: ${x.value} — ${x.meaning}`));renderList('#stage4-suitability-unknowns','Unknown / not assumed safe',a.unknowns||[]);renderList('#stage4-suitability-controls','Practical controls',a.controls||[]);renderHeat(a.heat,a.park?.name);}
function renderCompatibility(a){const root=$('#stage4-compatibility-result');if(!root)return;root.replaceChildren();const h=document.createElement('h3');h.textContent=`${a.mode==='GROUP'?'Group':'Pair'} compatibility review`;const names=document.createElement('p');names.textContent=(a.dogs||[]).map(d=>d.name).join(' · ');const status=document.createElement('p');status.className='stage4-gated';status.textContent='Numerical compatibility score: NOT ISSUED — expert policy gate pending';const g=document.createElement('p');g.textContent=a.guidance;root.append(h,names,status,g);renderList('#stage4-compatibility-factors','Comparison factors',(a.factors||[]).map(f=>`${f.factor}: ${f.dogs.map(d=>`${d.name}=${d.value}`).join(' | ')}`));renderList('#stage4-compatibility-unknowns','Unknown / current context',a.unknowns||[]);renderList('#stage4-compatibility-controls','Interaction controls',a.controls||[]);}
async function load(){try{const [dogs,park,heat]=await Promise.all([api('/api/dogs'),api('/api/parks?selected=1'),api('/api/heat')]);state.dogs=dogs.dogs||[];state.park=park.selectedPark||null;state.ready=true;renderDogOptions();renderHeat({shadeRecorded:heat.selectedPark?.shadeRecorded??'UNKNOWN',dogWaterRecorded:heat.selectedPark?.dogWaterRecorded??'UNKNOWN',tapWaterRecorded:heat.selectedPark?.tapWaterRecorded??'UNKNOWN',liveWeatherEnabled:heat.policy?.liveWeatherEnabled,surfaceHeatEstimateEnabled:heat.policy?.surfaceHeatEstimateEnabled},heat.selectedPark?.name??'Selected park');text('#stage4-suitability-status',state.park?'Stage 4 review ready. Select a mate and current observations.':'Choose a source-backed park above before reviewing suitability.');text('#stage4-compatibility-status',state.dogs.length>=2?'Select two dogs for a pair review, or 3–5 for a group review.':'Save at least two mate profiles first.');}catch(e){state.ready=false;updateButtons();const m=e.status===503?'Stage 4 database migration V003 is not applied yet. Decision-support controls remain safely disabled.':'Stage 4 decision-support data is unavailable. No risk assumption has been made.';text('#stage4-suitability-status',m);text('#stage4-compatibility-status',m);}}
function bind(){
 $('#stage4-suitability-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=new FormData(e.currentTarget),body=Object.fromEntries(form.entries());text('#stage4-suitability-status','Reviewing source facts and current observations…');try{const d=await api('/api/suitability',{method:'POST',headers:H4,body:JSON.stringify(body)});renderSuitability(d.assessment);text('#stage4-suitability-status','Review complete. Unknown information stayed unknown; no unapproved numeric score was produced.');}catch(x){text('#stage4-suitability-status',x.data?.error==='selected-park-required'?'Choose a source-backed park first.':x.status===503?'Stage 4 database migration V003 is required before this review can be saved.':'Suitability review was not saved. No safety assumption has been made.');}});
 $('#stage4-compatibility-form')?.addEventListener('submit',async e=>{e.preventDefault();const mode=$('#stage4-compatibility-mode')?.value||'PAIR',ids=[...document.querySelectorAll('input[name="stage4DogIds"]:checked')].map(x=>x.value);if((mode==='PAIR'&&ids.length!==2)||(mode==='GROUP'&&(ids.length<3||ids.length>5))){text('#stage4-compatibility-status',mode==='PAIR'?'Select exactly two saved mates.':'Select between three and five saved mates.');return;}text('#stage4-compatibility-status','Comparing owner-entered behaviour and care context…');try{const d=await api('/api/compatibility',{method:'POST',headers:H4,body:JSON.stringify({mode,dogIds:ids})});renderCompatibility(d.assessment);text('#stage4-compatibility-status','Compatibility review complete. No breed-only or safe/unsafe verdict was produced.');}catch(x){text('#stage4-compatibility-status',x.status===503?'Stage 4 database migration V003 is required first.':'Compatibility review was not saved.');}});
}
export async function initStage4(){renderScale();bind();await load();}
