const H5={'Content-Type':'application/json','X-Genevieve-Stage5':'1'};
const state={dogs:[],park:null,visits:[],solar:null,attendance:null,ready:false};
const $=s=>document.querySelector(s);
const text=(s,v)=>{const e=$(s);if(e)e.textContent=v;};
async function api(url,o={}){const r=await fetch(url,{cache:'no-store',credentials:'same-origin',...o});let d={};try{d=await r.json();}catch{}if(!r.ok){const e=new Error(d.error||`request-failed-${r.status}`);e.status=r.status;e.data=d;throw e;}return d;}
function option(value,label){const o=document.createElement('option');o.value=value;o.textContent=label;return o;}
function idempotency(prefix){return `${prefix}-${crypto.randomUUID()}`;}
function formatTime(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('en-AU',{hour:'numeric',minute:'2-digit'}).format(d);}
function renderDogs(){const s=$('#stage5-dog');if(!s)return;const current=s.value;s.replaceChildren(option('','Choose a saved mate'));for(const d of state.dogs)s.append(option(d.dog_id,d.name));if([...s.options].some(o=>o.value===current))s.value=current;}
function renderContext(){text('#stage5-selected-park',state.park?`${state.park.name}${state.park.locality?` · ${state.park.locality}`:''}`:'No source-backed park selected yet.');const button=$('#stage5-checkin-submit');if(button)button.disabled=!(state.ready&&state.park&&state.dogs.length);}
function visitCard(v){const root=document.createElement('article');root.className='stage5-visit-card';const h=document.createElement('div');h.className='stage5-visit-heading';const title=document.createElement('strong');const dog=state.dogs.find(d=>d.dog_id===v.dogId);title.textContent=dog?.name||'Saved mate';const badge=document.createElement('span');badge.className='stage5-private-badge';badge.textContent=v.privacyMode==='INCOGNITO'?'INCOGNITO · PRIVATE':'PRIVATE VISIT';h.append(title,badge);const meta=document.createElement('p');meta.textContent=`Arrived ${formatTime(v.arrivalAt)} · ${v.dogStatus.replaceAll('_',' ')} · ${v.ownerLocationState.replaceAll('_',' ')}`;const duty=document.createElement('p');duty.className='microcopy';duty.textContent=v.presenceStatus==='SUPERVISION_CONFIRMATION_DUE'?`Supervision confirmation due now · ${v.dutyIntervalMinutes}-minute duty interval`:`Supervision due ${formatTime(v.dutyDueAt)} · ${v.dutyIntervalMinutes}-minute duty interval`;const actions=document.createElement('div');actions.className='record-actions';const renew=document.createElement('button');renew.type='button';renew.className='compact-action';renew.textContent='I’m still supervising';renew.addEventListener('click',()=>mutate({action:'RENEW_SUPERVISION',visitId:v.visitId,dutyIntervalMinutes:v.dutyIntervalMinutes},'Supervision renewed. Your private visit remains active.'));const boundary=document.createElement('button');boundary.type='button';boundary.className='secondary compact-action';boundary.textContent='Check park boundary once';boundary.addEventListener('click',()=>oneShotBoundary(v));const left=document.createElement('button');left.type='button';left.className='secondary compact-action';left.textContent='I have left';left.addEventListener('click',()=>mutate({action:'SET_OWNER_LOCATION',visitId:v.visitId,ownerLocationState:'LEFT'},'Marked as left. Check out to close the private visit.'));const out=document.createElement('button');out.type='button';out.className='secondary compact-action';out.textContent='Check out';out.addEventListener('click',()=>mutate({action:'CHECK_OUT',visitId:v.visitId,idempotencyKey:idempotency('checkout')},'Checked out. Visit history is retained privately.'));actions.append(renew,boundary,left,out);root.append(h,meta,duty,actions);return root;}
function renderVisits(){const root=$('#stage5-active-visits');if(!root)return;root.replaceChildren();if(!state.visits.length){const p=document.createElement('p');p.className='empty-record';p.textContent='No active private visit. Check-in is voluntary.';root.append(p);return;}for(const v of state.visits)root.append(visitCard(v));}
function renderNight(d){state.solar=d.solar;const s=d.solar||{};text('#stage5-solar-phase',s.status==='CALCULATED'?`${s.phase.replaceAll('_',' ')} · sunrise ${s.sunriseLocal||'—'} · sunset ${s.sunsetLocal||'—'}`:'Solar status UNKNOWN — public attendance stays hidden.');const n=$('#stage5-night-banner');if(n){n.hidden=!s.nightPrivacy;n.textContent=d.nightSafety?.wording||'NIGHT SAFETY MODE ACTIVE — Live park attendance is hidden from sunset until sunrise to protect park-user privacy and safety.';}}
function renderAttendance(d){state.attendance=d.attendance;const a=d.attendance||{};text('#stage5-attendance-state',a.wording||d.message||'Public attendance remains hidden.');const panel=$('#stage5-attendance-panel');if(panel)panel.dataset.state=a.state||'HIDDEN';}
async function load(){try{const [dogs,park,visits,night,attendance]=await Promise.all([api('/api/dogs'),api('/api/parks?selected=1'),api('/api/checkin'),api('/api/night-safety'),api('/api/attendance')]);state.dogs=dogs.dogs||[];state.park=park.selectedPark||null;state.visits=visits.visits||[];state.ready=true;renderDogs();renderContext();renderVisits();renderNight(night);renderAttendance(attendance);text('#stage5-status','Stage 5 private presence controls ready. Public occupancy remains privacy-gated.');}catch(e){state.ready=false;renderContext();text('#stage5-status',e.status===503?'Stage 5 migration V004 is not applied yet. Check-in remains safely unavailable.':'Stage 5 private presence controls are unavailable. No attendance state has been inferred.');text('#stage5-attendance-state','Public attendance remains hidden.');}}
async function mutate(body,message){text('#stage5-status','Saving private visit state…');try{await api('/api/checkin',{method:'POST',headers:H5,body:JSON.stringify(body)});await load();text('#stage5-status',message);}catch(e){text('#stage5-status',e.data?.error==='dog-already-checked-in-elsewhere'?'This mate already has an active visit elsewhere. Check out first.':e.status===503?'Stage 5 migration V004 is required before this action can be saved.':'The private visit change was not saved. Existing state remains unchanged.');}}
function oneShotBoundary(v){if(!navigator.geolocation){text('#stage5-boundary-result','This device does not provide location. Boundary result: UNKNOWN.');return;}text('#stage5-boundary-result','Requesting one foreground location reading…');navigator.geolocation.getCurrentPosition(async position=>{const payload={visitId:v.visitId,dogId:v.dogId,userLatitude:position.coords.latitude,userLongitude:position.coords.longitude,accuracyM:position.coords.accuracy};try{const d=await api('/api/boundary',{method:'POST',headers:H5,body:JSON.stringify(payload)});text('#stage5-boundary-result',`${d.decision.replaceAll('_',' ')} — ${d.reason.replaceAll('-',' ')}. Precise location stored: no.`);}catch(e){text('#stage5-boundary-result',e.status===503?'Boundary check unavailable until V004 is applied.':'Boundary result: UNKNOWN. No precise location was retained.');}},()=>text('#stage5-boundary-result','Boundary result: UNKNOWN — location permission, freshness or accuracy was insufficient. No precise location was retained.'),{enableHighAccuracy:false,maximumAge:0,timeout:10000});}
function bind(){
 $('#stage5-checkin-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=new FormData(e.currentTarget),dogId=String(form.get('dogId')||'');if(!dogId){text('#stage5-status','Choose a saved mate before checking in.');return;}await mutate({action:'CHECK_IN',dogId,dogStatus:form.get('dogStatus'),privacyMode:form.get('privacyMode'),ownerLocationState:form.get('ownerLocationState'),dutyIntervalMinutes:Number(form.get('dutyIntervalMinutes')),idempotencyKey:idempotency('checkin')},'Checked in privately. Supervision timer is active; public attendance remains hidden.');});
 $('#stage5-refresh')?.addEventListener('click',load);
 const parkRoot=$('#today-selected-park'),dogRoot=$('#dog-list');
 if(parkRoot)new MutationObserver(()=>load()).observe(parkRoot,{childList:true,subtree:true});
 if(dogRoot)new MutationObserver(()=>load()).observe(dogRoot,{childList:true,subtree:true});
 window.addEventListener('focus',()=>load());
}
export async function initStage5(){bind();await load();}
