const H={'Content-Type':'application/json','X-Genevieve-Stage3':'1'};
const state={ready:false,dogs:[],park:null};
const $=s=>document.querySelector(s);
const text=(s,v)=>{const e=$(s);if(e)e.textContent=v;};
async function api(url,o={}){const r=await fetch(url,{cache:'no-store',credentials:'same-origin',...o});let d={};try{d=await r.json();}catch{}if(!r.ok){const e=new Error(d.error||`request-failed-${r.status}`);e.status=r.status;e.data=d;throw e;}return d;}
const payload=f=>Object.fromEntries(new FormData(f).entries());
function setField(f,n,v){const e=f?.elements?.namedItem(n);if(e)e.value=v??'';}
function chip(root,label,value){if(value===null||value===undefined||value==='')return;const s=document.createElement('span');s.textContent=`${label}: ${value}`;root.append(s);}
function age(p){const d=p.sourceUpdatedAt||p.fetchedAt||p.source?.lastVerifiedAt;if(!d)return'Unknown';const x=new Date(d);if(Number.isNaN(x.getTime()))return'Unknown';const n=Math.max(0,Math.floor((Date.now()-x.getTime())/86400000));return n===0?'Today':`${n} day${n===1?'':'s'}`;}
function renderPark(p){state.park=p||null;for(const sel of ['#today-selected-park','#journey-selected-park']){const r=$(sel);if(!r)continue;r.replaceChildren();const h=document.createElement('div');h.className='panel-title';h.textContent=sel.includes('today')?'Selected park':'Selected location';r.append(h);if(!p){const q=document.createElement('p');q.textContent='No park selected yet. Search Today and choose a source-backed park record.';r.append(q);continue;}const n=document.createElement('strong');n.className='selected-park-name';n.textContent=p.name;r.append(n);const loc=document.createElement('p');loc.textContent=[p.locality,p.stateCode,p.postcode].filter(Boolean).join(' · ')||'Location details not supplied';r.append(loc);const c=document.createElement('div');c.className='chips';chip(c,'Status',p.verificationStatus||'UNKNOWN');chip(c,'Source',p.source?.authorityName||'Unknown');chip(c,'Source age',age(p));r.append(c);if(p.officialRules){const q=document.createElement('p');q.className='microcopy';q.textContent=`Official-source rules: ${p.officialRules}`;r.append(q);}}}
function renderResults(parks){const r=$('#park-search-results');r.replaceChildren();if(!parks.length){const p=document.createElement('p');p.className='empty-record';p.textContent='No matching source-backed park records are stored. Nothing has been invented.';r.append(p);return;}for(const p of parks){const c=document.createElement('article');c.className='record-card park-record';const h=document.createElement('h3');h.textContent=p.name;const q=document.createElement('p');q.textContent=[p.locality,p.stateCode,p.postcode].filter(Boolean).join(' · ')||'Location not supplied';const m=document.createElement('div');m.className='chips';chip(m,'Verification',p.verificationStatus||'UNKNOWN');chip(m,'Authority',p.source?.authorityName||'Unknown');chip(m,'Freshness',age(p));const b=document.createElement('button');b.type='button';b.className='compact-action';b.textContent='Use this park';b.addEventListener('click',()=>selectPark(p));c.append(h,q,m,b);r.append(c);}}
async function selectPark(p){if(!state.ready){text('#park-search-status','Secure session unavailable; the park was not saved.');return;}try{await api('/api/parks',{method:'POST',headers:H,body:JSON.stringify({parkId:p.parkId})});renderPark(p);text('#park-search-status',`${p.name} selected. The same source-of-truth park is now carried into Journey.`);}catch(e){text('#park-search-status',e.status===503?'Stage 3 database is not configured.':'Park selection could not be saved.');}}
function enable(on){for(const s of ['#stage3-owner-fieldset','#stage3-dog-fieldset']){const e=$(s);if(e)e.disabled=!on;}}
async function session(){try{await api('/api/session',{method:'POST',headers:H,body:'{}'});state.ready=true;enable(true);text('#owner-form-status','Secure automatic session active. Profile changes can be saved.');text('#dog-form-status','Secure automatic session active. Mate profiles can be saved.');return true;}catch(e){state.ready=false;enable(false);const m=e.status===503?'Stage 3 database is not configured. Forms remain safely disabled.':'Secure automatic session could not be established. Forms remain safely disabled.';text('#owner-form-status',m);text('#dog-form-status',m);return false;}}
async function owner(){const d=await api('/api/profile');if(!d.profile)return;const f=$('#owner-profile-form'),m={publicName:'public_name',email:'email',phone:'phone',emergencyContactName:'emergency_contact_name',emergencyContactPhone:'emergency_contact_phone',accessibilityNotes:'accessibility_notes',privateMedicalNotes:'private_medical_notes',visibilityMode:'visibility_mode'};for(const [a,b]of Object.entries(m))setField(f,a,d.profile[b]);}
const dogMap={dogId:'dog_id',name:'name',breedMix:'breed_mix',birthDate:'birth_date',ageYears:'age_years',sizeGroup:'size_group',weightKg:'weight_kg',sex:'sex',desexedStatus:'desexed_status',energyLevel:'energy_level',playStyle:'play_style',socialComfort:'social_comfort',approachPreferences:'approach_preferences',likes:'likes',dislikes:'dislikes',knownTriggers:'known_triggers',sociabilityNotes:'sociability_notes',reactivityNotes:'reactivity_notes',toleranceNotes:'tolerance_notes',playIntensity:'play_intensity',resourceSharingNotes:'resource_sharing_notes',guardingNotes:'guarding_notes',extraCareNeeds:'extra_care_needs',swimmingAbility:'swimming_ability',mobilityLimitations:'mobility_limitations',favouriteToys:'favourite_toys',exerciseLevel:'exercise_level',confidenceLevel:'confidence_level',visibilityMode:'visibility_mode',microchipNumber:'microchip_number',councilRegistration:'council_registration',vaccinationNotes:'vaccination_notes',vaccinationDueDate:'vaccination_due_date',otherDocumentNotes:'other_document_notes',otherDocumentDueDate:'other_document_due_date',medicalConditions:'medical_conditions',allergies:'allergies',medications:'medications',veterinarianName:'veterinarian_name',veterinarianPhone:'veterinarian_phone',emergencyNotes:'emergency_notes'};
function fillDog(d){const f=$('#dog-profile-form');for(const[a,b]of Object.entries(dogMap))setField(f,a,d[b]);f.scrollIntoView({behavior:'smooth',block:'start'});}
function clearDog(){const f=$('#dog-profile-form');f.reset();setField(f,'dogId','');setField(f,'visibilityMode','GHOST');}
function renderDogs(){const r=$('#dog-list');r.replaceChildren();if(!state.dogs.length){const p=document.createElement('p');p.className='empty-record';p.textContent='No saved mate profiles yet.';r.append(p);return;}for(const d of state.dogs){const c=document.createElement('article');c.className='record-card';const h=document.createElement('h4');h.textContent=d.name;const p=document.createElement('p');p.textContent=[d.breed_mix,d.size_group,d.visibility_mode].filter(Boolean).join(' · ')||'Profile saved';const a=document.createElement('div');a.className='record-actions';const e=document.createElement('button');e.type='button';e.className='secondary compact-action';e.textContent='Edit';e.addEventListener('click',()=>fillDog(d));const z=document.createElement('button');z.type='button';z.className='secondary compact-action';z.textContent='Archive';z.addEventListener('click',()=>archive(d));a.append(e,z);c.append(h,p,a);r.append(c);}}
async function dogs(){const d=await api('/api/dogs');state.dogs=d.dogs||[];renderDogs();}
async function archive(d){try{await api('/api/dogs',{method:'DELETE',headers:H,body:JSON.stringify({dogId:d.dog_id})});await dogs();clearDog();text('#dog-form-status',`${d.name} was archived.`);}catch{text('#dog-form-status','The mate profile could not be archived. Nothing else changed.');}}
async function selected(){const d=await api('/api/parks?selected=1');renderPark(d.selectedPark||null);}
function bind(){
 $('#owner-profile-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!state.ready)return;text('#owner-form-status','Saving…');try{await api('/api/profile',{method:'PUT',headers:H,body:JSON.stringify(payload(e.currentTarget))});text('#owner-form-status','Profile saved to the Stage 3 source-of-truth layer.');}catch{text('#owner-form-status','Profile was not saved. Existing information remains unchanged.');}});
 $('#dog-profile-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!state.ready)return;const d=payload(e.currentTarget),method=d.dogId?'PUT':'POST';text('#dog-form-status','Saving…');try{await api('/api/dogs',{method,headers:H,body:JSON.stringify(d)});await dogs();clearDog();text('#dog-form-status','Mate profile saved. Restricted details remain owner-only.');}catch(x){text('#dog-form-status',x.data?.error==='dog-name-required'?'Dog name is required.':'Mate profile was not saved. Existing records remain unchanged.');}});
 $('#dog-form-reset')?.addEventListener('click',clearDog);
 $('#park-search-form')?.addEventListener('submit',async e=>{e.preventDefault();const q=$('#park-search-input')?.value?.trim()||'';if(q.length<2){text('#park-search-status','Enter at least two characters.');return;}text('#park-search-status','Searching source-backed park records…');try{const d=await api(`/api/parks?q=${encodeURIComponent(q)}`);renderResults(d.parks||[]);text('#park-search-status',`${(d.parks||[]).length} matching park record${(d.parks||[]).length===1?'':'s'} found. Check source and verification before choosing.`);}catch(x){renderResults([]);text('#park-search-status',x.status===503?'Stage 3 park database is not configured.':'Park search is unavailable. No safety assumption has been made.');}});
}
export async function initStage3(){bind();renderPark(null);if(!await session())return;const r=await Promise.allSettled([owner(),dogs(),selected()]);if(r.some(x=>x.status==='rejected'))text('#backend-status','Stage 3 connected · some profile data unavailable');}
