(() => {
  "use strict";
  const CFG = window.GENEVIEVE_CONFIG;
  const KEY = "genevieve_dogpark_live_state_v1";
  const dims = ["sociability","reactivity","energy","playIntensity","tolerance","resourceSharing","vulnerability"];
  const defaultState = {
    dogs:[
      {id:"mr-gruff",name:"Mr Gruff",dob:"2021-08-08",breed:"Companion dog",sociability:8,reactivity:3,energy:7,playIntensity:7,tolerance:7,resourceSharing:7,vulnerability:2,notes:"Owner-controlled profile. Calm introductions and current observations remain important."},
      {id:"molly-demo",name:"Molly (demonstration)",dob:"2020-05-12",breed:"Kelpie",sociability:8,reactivity:2,energy:9,playIntensity:8,tolerance:7,resourceSharing:6,vulnerability:2,notes:"High-energy demonstration profile."},
      {id:"charlie-demo",name:"Charlie (demonstration)",dob:"2018-02-10",breed:"Mixed breed",sociability:6,reactivity:5,energy:5,playIntensity:4,tolerance:6,resourceSharing:5,vulnerability:4,notes:"Prefers slower introductions."}
    ],
    checkins:[], affinities:[], predictions:[], outcomes:[], observations:[], evidence:[],
    privacy:{discoverable:true,livePresence:true,affinityAlerts:true,recommendations:true,learningParticipation:true,preciseLocation:false}
  };
  const parks = [
    {id:"labrador-broadwater",name:"Labrador Broadwater Dog Exercise Area",suburb:"Labrador QLD",capacity:28,fenced:false,quiet:false,water:true,shade:true,accessible:true,beach:true,warning:"Demonstration record — confirm current council signs, boundaries, tide and conditions."},
    {id:"southport-small",name:"Southport Small Fenced Dog Park",suburb:"Southport QLD",capacity:8,fenced:true,quiet:true,water:true,shade:true,accessible:true,beach:false,warning:"Demonstration record — confirm local rules and current maintenance."},
    {id:"robina-enclosed",name:"Robina Enclosed Dog Park",suburb:"Robina QLD",capacity:16,fenced:true,quiet:false,water:true,shade:true,accessible:true,beach:false,warning:"Demonstration record — monitor mixed-size play and peak periods."},
    {id:"palm-beach-demo",name:"Palm Beach Off-Leash Beach Area",suburb:"Palm Beach QLD",capacity:45,fenced:false,quiet:false,water:false,shade:false,accessible:false,beach:true,warning:"Demonstration record — verify off-leash boundaries, tide, heat and council requirements."}
  ];
  const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
  const safe = v => String(v ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const uid = p => `${p}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
  function load(){try{return {...structuredClone(defaultState),...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return structuredClone(defaultState)}}
  let state=load();
  function save(){localStorage.setItem(KEY,JSON.stringify(state))}
  function evidence(type,payload){state.evidence.unshift({id:uid("ev"),type,payload,version:CFG.version,time:new Date().toISOString()});state.evidence=state.evidence.slice(0,1000);save();renderSnapshot()}
  function download(name,text,type="application/json"){const b=new Blob([text],{type});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function channel(){const q=new URLSearchParams(location.search).get("channel");return ["web","apple","google"].includes(q)?q:(CFG.defaultChannel||"web")}
  function setScreen(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));history.replaceState(null,"",`#${id}`);scrollTo({top:0,behavior:"smooth"})}
  function dogOptions(){return state.dogs.map(d=>`<option value="${safe(d.id)}">${safe(d.name)}</option>`).join("")}
  function parkOptions(){return parks.map(p=>`<option value="${safe(p.id)}">${safe(p.name)}</option>`).join("")}
  function refreshSelects(){$$('select[name="dog"],select[name="dogA"],select[name="dogB"],select[name="fromDog"],select[name="toDog"]').forEach(s=>{const val=s.value;s.innerHTML=dogOptions();if([...s.options].some(o=>o.value===val))s.value=val});$$('select[name="park"]').forEach(s=>{const val=s.value;s.innerHTML=parkOptions();if([...s.options].some(o=>o.value===val))s.value=val});renderPredictionSelect()}
  function renderDogs(){const n=$('#dogList');n.innerHTML=state.dogs.map(d=>`<article class="dog-card"><h3>${safe(d.name)}</h3><p>${safe(d.breed||"Breed not recorded")} ${d.dob?`· born ${safe(d.dob)}`:""}</p><div class="chips">${dims.map(k=>`<span class="chip">${safe(k)} ${Number(d[k]).toFixed(0)}/10</span>`).join("")}</div><p>${safe(d.notes||"")}</p><div class="button-row"><button data-edit-dog="${safe(d.id)}" class="secondary">Edit</button>${d.id==='mr-gruff'?"":`<button data-delete-dog="${safe(d.id)}" class="danger">Delete</button>`}</div></article>`).join("")||'<p class="empty">No dogs saved.</p>'}
  function renderParks(){const q=($('#parkSearch')?.value||"").toLowerCase();const need=$('#parkNeed')?.value||"";const list=parks.filter(p=>{const text=`${p.name} ${p.suburb} ${p.warning}`.toLowerCase();return(!q||text.includes(q))&&(!need||Boolean(p[need]))});$('#parkList').innerHTML=list.map(p=>`<article class="card park-card"><h3>${safe(p.name)}</h3><p><b>${safe(p.suburb)}</b> · demonstration capacity ${p.capacity}</p><div class="chips"><span class="chip">${p.fenced?'fenced':'not fully fenced'}</span><span class="chip">${p.quiet?'quieter':'can be busy'}</span>${p.water?'<span class="chip">water</span>':''}${p.shade?'<span class="chip">shade</span>':''}${p.accessible?'<span class="chip">accessible</span>':''}${p.beach?'<span class="chip">beach</span>':''}</div><p class="muted">${safe(p.warning)}</p><button data-use-park="${safe(p.id)}">Use for compatibility</button></article>`).join("")}
  function renderCheckins(){const n=$('#checkinList');n.innerHTML=state.checkins.map(c=>{const d=state.dogs.find(x=>x.id===c.dogId),p=parks.find(x=>x.id===c.parkId);return `<article class="checkin-card"><h3>${safe(d?.name||'Dog')}</h3><p>${safe(p?.name||'Park')} · ${new Date(c.time).toLocaleString('en-AU')}</p><div class="chips">${c.incognito?'<span class="chip">incognito</span>':''}${c.needsSpace?'<span class="chip">needs space</span>':''}</div><button data-checkout="${safe(c.id)}" class="secondary">Check out</button></article>`}).join("")||'<p class="empty">No dogs checked in on this device.</p>';renderSnapshot()}
  function baseScore(a,b){const w={sociability:1.1,reactivity:1.55,energy:1,playIntensity:1.25,tolerance:1.45,resourceSharing:1.3,vulnerability:.9};let dist=0,max=0;dims.forEach(k=>{dist+=Math.abs(Number(a[k])-Number(b[k]))*w[k];max+=10*w[k]});let s=100*(1-dist/max);s-=Math.max(0,a.reactivity+b.reactivity-12)*2.3;s-=Math.max(0,Math.abs(a.playIntensity-b.tolerance)-4)*2.5;s-=Math.max(0,Math.abs(b.playIntensity-a.tolerance)-4)*2.5;s-=Math.max(0,a.vulnerability+b.energy-14)*1.7;s-=Math.max(0,b.vulnerability+a.energy-14)*1.7;return Math.max(0,Math.min(100,s))}
  function classify(s){if(s>=80)return{c:'green',label:'Higher predicted compatibility',action:'A normal supervised introduction may be considered.'};if(s>=65)return{c:'yellow',label:'Conditional compatibility',action:'Use a calm staged introduction and monitor closely.'};if(s>=45)return{c:'amber',label:'Elevated interaction risk',action:'Reduce stimulation, create space or choose another time.'};return{c:'red',label:'High predicted interaction risk',action:'Avoid direct interaction under the current conditions.'}}
  function predict(aId,bId,parkId,pop=10,energy=5,reason='pair_check'){const a=state.dogs.find(d=>d.id===aId),b=state.dogs.find(d=>d.id===bId),p=parks.find(x=>x.id===parkId);if(!a||!b||aId===bId)return null;const base=baseScore(a,b);const density=Number(pop)/Math.max(1,p.capacity);const penalty=Math.max(0,density-.55)*42+Math.max(0,Number(energy)-6.5)*2.2+Math.max(0,(a.reactivity+b.reactivity)/2-6)*density*4;const final=Math.max(0,Math.min(100,base-penalty));const cls=classify(final);const rec={id:uid('pred'),dogAId:a.id,dogBId:b.id,dogAName:a.name,dogBName:b.name,parkId:p.id,parkName:p.name,baseScore:+base.toFixed(1),score:+final.toFixed(1),population:Number(pop),capacity:p.capacity,density:+density.toFixed(2),groupEnergy:Number(energy),classification:cls,reason,time:new Date().toISOString(),modelVersion:CFG.version};state.predictions.unshift(rec);state.predictions=state.predictions.slice(0,200);evidence('compatibility_prediction',rec);return rec}
  function predictionHtml(r){return `<article class="prediction ${r.classification.c}"><h3>${safe(r.dogAName)} + ${safe(r.dogBName)}</h3><div class="score">${r.score}%</div><div class="scorebar"><span style="width:${r.score}%"></span></div><p><b>${safe(r.classification.label)}</b></p><p>${safe(r.classification.action)}</p><p class="small">Base ${r.baseScore}% · ${safe(r.parkName)} · population ${r.population}/${r.capacity} · group energy ${r.groupEnergy}/10</p><p class="muted">Decision support only — not a safety guarantee.</p></article>`}
  function renderPredictionSelect(){const s=$('#outcomeForm select[name="prediction"]');if(!s)return;s.innerHTML=state.predictions.slice(0,30).map(p=>`<option value="${safe(p.id)}">${safe(p.dogAName)} + ${safe(p.dogBName)} · ${p.score}%</option>`).join("")||'<option value="">Run a prediction first</option>'}
  function renderAffinity(){const n=$('#affinityList');n.innerHTML=state.affinities.map(a=>{const f=state.dogs.find(d=>d.id===a.fromDogId),t=state.dogs.find(d=>d.id===a.toDogId),p=parks.find(x=>x.id===a.parkId);return `<article class="affinity-card"><h3>${safe(f?.name)} → ${safe(t?.name)}</h3><p>${safe(a.mode)} · ${safe(a.status)} · ${safe(p?.name)}</p><label>Private removal reason<select data-removal-reason="${safe(a.id)}"><option value="owner_preference">Owner preference</option><option value="incompatible_play">Incompatible play</option><option value="reactivity">Reactivity</option><option value="resource_guarding">Resource guarding</option><option value="stress">Stress response</option></select></label><button data-remove-affinity="${safe(a.id)}" class="danger">Remove relationship</button></article>`}).join("")||'<p class="empty">No best-mate relationships saved.</p>'}
  function renderPrivacy(){const labels={discoverable:'Allow dog profile discoverability',livePresence:'Allow live presence visibility',affinityAlerts:'Allow best-mate proximity alerts',recommendations:'Allow prospective companion recommendations',learningParticipation:'Use outcome feedback to refine local profiles',preciseLocation:'Allow precise location when a future production feature requires it'};$('#privacyControls').innerHTML=Object.entries(labels).map(([k,v])=>`<label class="toggle"><input type="checkbox" name="${k}" ${state.privacy[k]?'checked':''}> ${safe(v)}</label>`).join("")}
  function renderPlans(){const ch=channel();$('#modePill').textContent=`${ch==='web'?'Web / Vercel':ch==='apple'?'Apple App Store':'Google Play'} mode · v${CFG.version}`;const msg={web:'Web purchases use verified Stripe Payment Links. Apple Pay or Google Pay can appear on Stripe’s hosted checkout when supported by the customer’s device and browser.',apple:'Apple build mode: premium digital subscriptions must be purchased through Apple In-App Purchase. External web payment buttons are not shown.',google:'Google Play build mode: premium digital subscriptions must be purchased through Google Play Billing. External web payment buttons are not shown.'}[ch];$('#billingChannelMessage').textContent=msg;$('#planList').innerHTML=CFG.products.map(p=>{const webReady=Boolean(p.stripePaymentLink);const nativeReady=window.GenevieveNativeBilling.isAvailable();const enabled=ch==='web'?webReady:nativeReady;return `<article class="card plan-card ${enabled?'':'disabled'}"><p class="eyebrow">${safe(p.name)}</p><div class="price">${safe(p.priceLabel)}</div><p><b>${safe(p.periodLabel)}</b></p><p>${safe(p.audience)}</p><p>${safe(p.trialLabel)}. Then ${safe(p.priceLabel)} ${safe(p.periodLabel)}, automatically renewing until cancelled.</p><button data-buy="${safe(p.id)}" ${enabled?'':'disabled'}>${ch==='web'?'Continue to secure web checkout':'Subscribe through store'}</button><p class="muted">${enabled?'Payment route configured.':ch==='web'?'Stripe link not mapped yet.':'Native billing bridge not connected yet.'}</p></article>`}).join("")}
  function renderSnapshot(){const checked=state.checkins.length;const latest=state.predictions[0];$('#snapshot').innerHTML=`<p><b>${state.dogs.length}</b> dog profiles · <b>${checked}</b> local check-ins · <b>${state.affinities.length}</b> best-mate links</p>${latest?`<div class="answer ${latest.classification.c}"><b>Latest check: ${latest.score}%</b><br>${safe(latest.dogAName)} + ${safe(latest.dogBName)} at ${safe(latest.parkName)}</div>`:'<p class="muted">No compatibility assessment recorded yet.</p>'}`;$('#evidenceCount').textContent=`${state.evidence.length} dated evidence events saved on this device.`;if(latest)$('#todayAnswer').className=`answer ${latest.classification.c}`,$('#todayAnswer').innerHTML=`<b>${latest.score}% — ${safe(latest.classification.label)}</b><br>${safe(latest.classification.action)}`}
  async function runLaunchCheck(){const ch=channel();const tests=[{name:'Root app loaded',ok:true},{name:'Public support email configured',ok:Boolean(CFG.publicSupportEmail),block:true},{name:'Public website URL configured',ok:Boolean(CFG.publicWebsiteUrl),block:true},{name:'Four product IDs present',ok:CFG.products.length===4},{name:'All product IDs unique',ok:new Set(CFG.products.map(p=>p.id)).size===CFG.products.length},{name:'Web Stripe links mapped',ok:CFG.products.every(p=>Boolean(p.stripePaymentLink)),block:ch==='web'},{name:'Legal pages linked',ok:true},{name:'Local data export and deletion available',ok:true},{name:'Optional backend configured',ok:window.GenevieveBackend.enabled,warn:true}];if(window.GenevieveBackend.enabled){const h=await window.GenevieveBackend.health();tests.push({name:'Backend health check',ok:h.ok,block:true,detail:h.message})}$('#launchResults').innerHTML=tests.map(t=>`<div class="${t.ok?'launch-pass':t.block?'launch-block':'launch-warn'}"><b>${t.ok?'PASS':t.block?'BLOCKED':'NOT CONNECTED'} — ${safe(t.name)}</b>${t.detail?`<br>${safe(t.detail)}`:''}</div>`).join('');evidence('launch_check',{channel:ch,tests})}
  function boot(){
    $$('.tabs [data-tab]').forEach(b=>b.addEventListener('click',()=>setScreen(b.dataset.tab)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>setScreen(b.dataset.go)));
    $$('input[type="range"]').forEach(r=>r.addEventListener('input',()=>r.nextElementSibling.textContent=r.value));
    refreshSelects();renderDogs();renderParks();renderCheckins();renderAffinity();renderPrivacy();renderPlans();renderSnapshot();
    const hash=location.hash.slice(1);if(document.getElementById(hash))setScreen(hash);
    $('#dogForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('id')||uid('dog');const dog={id,name:String(f.get('name')).trim(),dob:f.get('dob'),breed:f.get('breed'),notes:f.get('notes')};dims.forEach(k=>dog[k]=Number(f.get(k)));const i=state.dogs.findIndex(d=>d.id===id);if(i>=0)state.dogs[i]=dog;else state.dogs.push(dog);evidence(i>=0?'dog_updated':'dog_created',{dogId:id,name:dog.name});e.currentTarget.reset();e.currentTarget.elements.id.value='';$$('#dogForm input[type="range"]').forEach(r=>{r.nextElementSibling.textContent=r.value});renderDogs();refreshSelects()});
    $('#dogForm').addEventListener('reset',e=>setTimeout(()=>{e.currentTarget.elements.id.value='';$$('#dogForm input[type="range"]').forEach(r=>r.nextElementSibling.textContent=r.value)},0));
    document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit-dog]');if(edit){const d=state.dogs.find(x=>x.id===edit.dataset.editDog),f=$('#dogForm');Object.entries(d).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v});$$('#dogForm input[type="range"]').forEach(r=>r.nextElementSibling.textContent=r.value);setScreen('dogs');f.elements.name.focus()}const del=e.target.closest('[data-delete-dog]');if(del&&confirm('Delete this dog profile from this device?')){const id=del.dataset.deleteDog;state.dogs=state.dogs.filter(d=>d.id!==id);state.checkins=state.checkins.filter(c=>c.dogId!==id);state.affinities=state.affinities.filter(a=>a.fromDogId!==id&&a.toDogId!==id);evidence('dog_deleted',{dogId:id});renderDogs();renderCheckins();renderAffinity();refreshSelects()}const use=e.target.closest('[data-use-park]');if(use){setScreen('compatibility');$('#compatibilityForm select[name="park"]').value=use.dataset.usePark}const out=e.target.closest('[data-checkout]');if(out){state.checkins=state.checkins.filter(c=>c.id!==out.dataset.checkout);evidence('check_out',{checkinId:out.dataset.checkout});renderCheckins()}const rem=e.target.closest('[data-remove-affinity]');if(rem){const id=rem.dataset.removeAffinity,reason=document.querySelector(`[data-removal-reason="${CSS.escape(id)}"]`)?.value||'owner_preference';const a=state.affinities.find(x=>x.id===id);state.affinities=state.affinities.filter(x=>x.id!==id);evidence('affinity_removed',{affinity:a,reason,private:true});renderAffinity()}const buy=e.target.closest('[data-buy]');if(buy){const p=CFG.products.find(x=>x.id===buy.dataset.buy),ch=channel();if(ch==='web'){if(p?.stripePaymentLink){location.href=p.stripePaymentLink}else $('#billingResult').className='answer red',$('#billingResult').innerHTML='<b>Payment link not configured.</b><br>Map and verify this product in config.js before public paid launch.'}else{const ok=window.GenevieveNativeBilling.purchase(p.id);$('#billingResult').className=`answer ${ok?'green':'red'}`;$('#billingResult').innerHTML=ok?'<b>Store purchase requested.</b>':'<b>Native store billing is not connected.</b><br>The web build has correctly refused to open an external payment route.'}}});
    $('#parkSearch').addEventListener('input',renderParks);$('#parkNeed').addEventListener('change',renderParks);
    $('#compatibilityForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),r=predict(f.get('dogA'),f.get('dogB'),f.get('park'),f.get('population'),f.get('groupEnergy'));$('#compatibilityResult').innerHTML=r?predictionHtml(r):'<b>Choose two different dogs.</b>';renderPredictionSelect()});
    $('#recommendationForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!state.privacy.recommendations){$('#recommendationList').innerHTML='<p>Recommendations are disabled in Privacy Controls.</p>';return}const id=f.get('dog'),p=f.get('park'),results=state.dogs.filter(d=>d.id!==id).map(d=>predict(id,d.id,p,10,5,'prospective_recommendation')).sort((a,b)=>b.score-a.score);$('#recommendationList').innerHTML=results.map(predictionHtml).join('')||'<p>No other dogs available.</p>';renderPredictionSelect()});
    $('#outcomeForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),pred=state.predictions.find(p=>p.id===f.get('prediction'));if(!pred)return;const outcome={id:uid('out'),predictionId:pred.id,outcome:f.get('outcome'),note:f.get('note'),time:new Date().toISOString()};state.outcomes.unshift(outcome);if(state.privacy.learningParticipation){const map={positive:.35,neutral:0,stressful:-.35,conflict:-.65},adj=map[outcome.outcome]||0;[pred.dogAId,pred.dogBId].forEach(id=>{const d=state.dogs.find(x=>x.id===id);if(d){d.sociability=Math.max(0,Math.min(10,d.sociability+adj));d.tolerance=Math.max(0,Math.min(10,d.tolerance+adj));if(adj<0)d.reactivity=Math.max(0,Math.min(10,d.reactivity-adj))}})}evidence('interaction_outcome',outcome);renderDogs();e.currentTarget.reset()});
    $('#affinityForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('fromDog')===f.get('toDog'))return alert('Choose two different dogs.');const a={id:uid('aff'),fromDogId:f.get('fromDog'),toDogId:f.get('toDog'),mode:f.get('mode'),status:f.get('mode')==='mutual'?'pending reciprocal consent':'active',parkId:f.get('park'),time:new Date().toISOString()};state.affinities.unshift(a);evidence('affinity_created',a);renderAffinity()});
    $('#alertCheckForm').addEventListener('submit',e=>{e.preventDefault();const parkId=new FormData(e.currentTarget).get('park');if(!state.privacy.affinityAlerts||!state.privacy.livePresence){$('#affinityAlerts').innerHTML='<div class="answer amber">Affinity alerts or presence visibility are disabled.</div>';return}const visible=new Set(state.checkins.filter(c=>c.parkId===parkId&&!c.incognito).map(c=>c.dogId));const matches=state.affinities.filter(a=>a.parkId===parkId&&a.status==='active'&&visible.has(a.toDogId));$('#affinityAlerts').innerHTML=matches.length?matches.map(a=>`<div class="answer green"><b>${safe(state.dogs.find(d=>d.id===a.toDogId)?.name)} is visible at this preferred park.</b></div>`).join(''):'<div class="answer amber">No eligible best mate is currently visible at this park.</div>'});
    $('#checkinForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),dogId=f.get('dog');state.checkins=state.checkins.filter(c=>c.dogId!==dogId);const c={id:uid('checkin'),dogId,parkId:f.get('park'),incognito:f.get('incognito')==='on',needsSpace:f.get('needsSpace')==='on',time:new Date().toISOString()};state.checkins.unshift(c);evidence('check_in',c);renderCheckins()});
    $('#privacyForm').addEventListener('submit',e=>{e.preventDefault();Object.keys(state.privacy).forEach(k=>state.privacy[k]=Boolean(e.currentTarget.elements[k]?.checked));evidence('privacy_settings_updated',state.privacy);renderPrivacy();alert('Privacy settings saved on this device.')});
    $('#exportEvidence').addEventListener('click',()=>{evidence('evidence_export',{count:state.evidence.length});download(`GENEVIEVE-patent-evidence-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({exportedAt:new Date().toISOString(),version:CFG.version,evidence:state.evidence,predictions:state.predictions,outcomes:state.outcomes,affinities:state.affinities},null,2))});
    $('#exportAllData').addEventListener('click',()=>download(`GENEVIEVE-my-data-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({exportedAt:new Date().toISOString(),state},null,2)));
    $('#deleteAllData').addEventListener('click',()=>{if(confirm('Delete all locally stored GENEVIEVE Dog Park data from this browser? This cannot be undone and does not cancel a subscription.')){localStorage.removeItem(KEY);location.reload()}});
    $('#restorePurchases').addEventListener('click',()=>{const ch=channel();if(ch==='web'){$('#billingResult').className='answer amber';$('#billingResult').innerHTML='<b>Web subscriptions are managed through the original Stripe customer portal or support route.</b>'}else{const ok=window.GenevieveNativeBilling.restore();$('#billingResult').className=`answer ${ok?'green':'red'}`;$('#billingResult').textContent=ok?'Restore request sent to the store.':'Native billing bridge is not connected.'}});
    $('#runLaunchCheck').addEventListener('click',runLaunchCheck);
    if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
    evidence('app_loaded',{channel:channel(),backendConfigured:window.GenevieveBackend.enabled});
  }
  document.addEventListener('DOMContentLoaded',boot);
})();
