import crypto from 'node:crypto';
import { neon } from '@neondatabase/serverless';
export const SESSION_COOKIE='genevieve_stage3_session';
const MAX_BODY_BYTES=32*1024;
export function getSql(){return process.env.DATABASE_URL?neon(process.env.DATABASE_URL):null;}
export function setNoStore(r){r.setHeader('Cache-Control','no-store, private');r.setHeader('Content-Type','application/json; charset=utf-8');r.setHeader('X-Content-Type-Options','nosniff');}
export function methodNotAllowed(r,a){r.setHeader('Allow',a.join(', '));return r.status(405).json({ok:false,error:'method-not-allowed'});}
export function unavailable(r){return r.status(503).json({ok:false,error:'stage3-database-not-configured',message:'Stage 3 secure persistence is unavailable until the server database is configured.'});}
export function parseCookies(h=''){return h.split(';').reduce((o,p)=>{const i=p.indexOf('=');if(i<0)return o;const k=p.slice(0,i).trim(),v=p.slice(i+1).trim();if(!k)return o;try{o[k]=decodeURIComponent(v);}catch{o[k]=v;}return o;},{});}
export function tokenHash(t){return crypto.createHash('sha256').update(t).digest('hex');}
export async function readJson(req){const len=Number(req.headers?.['content-length']??req.headers?.get?.('content-length')??0);if(Number.isFinite(len)&&len>MAX_BODY_BYTES)throw Object.assign(new Error('payload-too-large'),{statusCode:413});if(req.body&&typeof req.body==='object'&&!Buffer.isBuffer(req.body))return req.body;if(typeof req.body==='string')return req.body?JSON.parse(req.body):{};let raw='';if(req&&Symbol.asyncIterator in req){for await(const c of req){raw+=c.toString();if(Buffer.byteLength(raw)>MAX_BODY_BYTES)throw Object.assign(new Error('payload-too-large'),{statusCode:413});}}return raw?JSON.parse(raw):{};}
export function cleanString(v,n=500){if(v===null||v===undefined)return null;const t=String(v).replace(/[\u0000-\u001F\u007F]/g,' ').trim();return t?t.slice(0,n):null;}
export function cleanDate(v){const t=cleanString(v,10);if(!t)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(t))throw Object.assign(new Error('invalid-date'),{statusCode:400});return t;}
export function cleanNumber(v,min,max){if(v===''||v===null||v===undefined)return null;const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw Object.assign(new Error('invalid-number'),{statusCode:400});return n;}
export function cleanEnum(v,a,f=null){const t=cleanString(v,40);if(!t)return f;if(!a.includes(t))throw Object.assign(new Error('invalid-option'),{statusCode:400});return t;}
export function requireStage3Mutation(req){const m=req.headers?.['x-genevieve-stage3']??req.headers?.get?.('x-genevieve-stage3');if(String(m??'')!=='1')throw Object.assign(new Error('mutation-marker-required'),{statusCode:403});}
export async function findSession(sql,req){const h=req.headers?.cookie??req.headers?.get?.('cookie')??'';const token=parseCookies(h)[SESSION_COOKIE];if(!token||token.length<32||token.length>200)return null;const hash=tokenHash(token);const rows=await sql`SELECT session_id FROM stage3.device_sessions WHERE token_hash=${hash} AND revoked_at IS NULL LIMIT 1`;const s=rows[0]??null;if(s)await sql`UPDATE stage3.device_sessions SET last_seen_at=now() WHERE session_id=${s.session_id}`;return s;}
export async function requireSession(sql,req){const s=await findSession(sql,req);if(!s)throw Object.assign(new Error('session-required'),{statusCode:401});return s;}
export async function createAutomaticSession(sql,r){const token=crypto.randomBytes(32).toString('base64url'),hash=tokenHash(token),id=crypto.randomUUID();await sql`INSERT INTO stage3.device_sessions (session_id,token_hash) VALUES (${id},${hash})`;await sql`INSERT INTO stage3.audit_events (session_id,event_type,entity_type,entity_id,detail) VALUES (${id},'session_created','session',${id},${JSON.stringify({mode:'automatic-device-session'})}::jsonb)`;r.setHeader('Set-Cookie',`${SESSION_COOKIE}=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=15552000`);return {session_id:id};}
export async function audit(sql,s,e,t,id,d={}){await sql`INSERT INTO stage3.audit_events (session_id,event_type,entity_type,entity_id,detail) VALUES (${s},${e},${t},${id},${JSON.stringify(d??{})}::jsonb)`;}
export function sendError(r,e){const s=Number(e?.statusCode)||500;if(s>=500)console.error('Stage 3 API error',e instanceof Error?e.message:'unknown-error');return r.status(s).json({ok:false,error:s>=500?'stage3-server-error':(e?.message||'invalid-request')});}
